IMPORT_EMPLOYEES_EXCEL_MAP = {
    "code": "Số hợp đồng",
    "name": "HỌ VÀ TÊN",
    "gender": "GIỚI TÍNH",
    "department_code": "MÃ BỘ PHẬN",
    "position_code": "MÃ CHỨC VỤ",
    "mst": "MST",
    "date_of_birth": "NĂM SINH",
    "cccd": "SỐ CCCD",
    "cccd_date": "NGÀY CẤP",
    "cccd_place": "NƠI CẤP",
    "permanent_addr": "ĐỊA CHỈ THƯỜNG TRÚ",
    "start_date": "NGÀY BẮT ĐẦU HỢP ĐỒNG",
    "end_date": "NGÀY KẾT THÚC HỢP ĐỒNG",
    "is_probation": "THỬ VIỆC",
    "salary": "LƯƠNG CƠ BẢN",
    "housing_benefit": "PHỤ CẤP TIỀN NHÀ",
    "attendant_benefit": "PHỤ CẤP CHUYÊN CẦN",
    "transportation_benefit": "PHỤ CẤP ĐI LẠI",
    "meal_benefit": "PHỤ CẤP TIỀN ĂN",
    "toxic_benefit": "PHỤ CẤP ĐỘC HẠI",
    "phone_benefit": "PHỤ CẤP ĐIỆN THOẠI",
}


DTYPES_MAP = {
    "code": str,
    "name": str,
    "gender": str,
    "department_code": str,
    "position_code": str,
    "mst": str,
    "date_of_birth": str,
    "cccd": str,
    "cccd_date": str,
    "cccd_place": str,
    "permanent_addr": str,
    "start_date": str,
    "end_date": str,
    "is_probation": str,
    "salary": str,
    "housing_benefit": str,
    "attendant_benefit": str,
    "transportation_benefit": str,
    "meal_benefit": str,
    "toxic_benefit": str,
    "phone_benefit": str,
}
