"""Remove company_id from schedule details

Revision ID: 056510f6b412
Revises: 60567c73b757
Create Date: 2025-01-12 00:44:58.032403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "056510f6b412"
down_revision: Union[str, None] = "60567c73b757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "schedule_details_company_id_fkey", "schedule_details", type_="foreignkey"
    )
    op.drop_column("schedule_details", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_details",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "schedule_details_company_id_fkey",
        "schedule_details",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###
