"""add is_offboard for employee

Revision ID: 076c14c8ef75
Revises: 816b2a3426fb
Create Date: 2024-11-01 17:29:44.567771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "076c14c8ef75"
down_revision: Union[str, None] = "816b2a3426fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("employees", sa.Column("is_offboard", sa.Boolean(), nullable=True))
    connection = op.get_bind()

    # Update null cccd_date to current date
    connection.execute(
        sa.text(
            """
        UPDATE employees
        SET is_offboard = FALSE
        WHERE is_offboard IS NULL
    """
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "is_offboard", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "is_offboard")
    # ### end Alembic commands ###
