"""refactor schedule_details table

Revision ID: 1874d0773bf8
Revises: fe374b53155e
Create Date: 2024-07-25 11:37:03.567307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1874d0773bf8"
down_revision: Union[str, None] = "fe374b53155e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(length=3), nullable=False),
        sa.Column("created_by", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.PrimaryKeyConstraint("id", "schedule_id", "shift_id", "day"),
    )
    op.drop_table("schedule_shift_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_shift_association",
        sa.Column("schedule_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("shift_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("day", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name="schedule_shift_association_schedule_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shifts.id"], name="schedule_shift_association_shift_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "schedule_id", "shift_id", "day", name="schedule_shift_association_pkey"
        ),
    )
    op.drop_table("schedule_details")
    # ### end Alembic commands ###
