"""refactor schedule_shift_association table

Revision ID: 1ba67378bf85
Revises: 9930917b029a
Create Date: 2024-07-25 10:54:19.498014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ba67378bf85"
down_revision: Union[str, None] = "9930917b029a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_shift_association",
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id", "shift_id", "day"),
    )
    op.drop_table("schedule_details")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_details",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("schedule_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("shift_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("day", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.Column(
            "created_by", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["schedules.id"], name="schedule_details_schedule_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shifts.id"], name="schedule_details_shift_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "id", "schedule_id", "shift_id", "day", name="schedule_details_pkey"
        ),
    )
    op.drop_table("schedule_shift_association")
    # ### end Alembic commands ###
