"""first version

Revision ID: 1f09833839ed
Revises:
Create Date: 2024-06-22 16:36:52.976722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f09833839ed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracttypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("number_of_months", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("is_probation", sa.Boolean(), nullable=False),
        sa.Column(
            "tax_policy",
            sa.Enum("Progressive", "Fixed", name="taxtype"),
            nullable=False,
        ),
        sa.Column(
            "insurance_policy",
            sa.Enum(
                "BasicSalary", "TotalSalary", "CustomByEmployee", name="insurancetype"
            ),
            nullable=False,
        ),
        sa.Column("template", sa.LargeBinary(), nullable=True),
        sa.Column("created_by", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "insurance_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column(
            "based_on",
            sa.Enum(
                "BasicSalary", "TotalSalary", "CustomByEmployee", name="insurancetype"
            ),
            nullable=False,
        ),
        sa.Column("company_percentage", sa.Float(), nullable=False),
        sa.Column("employee_percentage", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "tax_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column(
            "tax_type", sa.Enum("Progressive", "Fixed", name="taxtype"), nullable=False
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.Enum("Male", "Female", name="gender"), nullable=False),
        sa.Column(
            "nationality", sa.Enum("VN", "JP", name="nationality"), nullable=True
        ),
        sa.Column("ethnic", sa.String(length=10), nullable=True),
        sa.Column("religion", sa.String(length=30), nullable=True),
        sa.Column("cccd", sa.String(length=30), nullable=False),
        sa.Column("cccd_date", sa.Date(), nullable=True),
        sa.Column("cccd_place", sa.String(length=255), nullable=True),
        sa.Column("domicile", sa.String(length=255), nullable=True),
        sa.Column("permanent_addr", sa.String(length=255), nullable=True),
        sa.Column("temp_addr", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("academic_level", sa.String(length=30), nullable=True),
        sa.Column("bank_account", sa.String(length=30), nullable=True),
        sa.Column("bank_holder_name", sa.String(length=30), nullable=True),
        sa.Column("bank_name", sa.String(length=30), nullable=True),
        sa.Column("mst", sa.String(length=30), nullable=False),
        sa.Column("kcb_number", sa.String(length=30), nullable=True),
        sa.Column("hospital_info", sa.String(length=255), nullable=True),
        sa.Column("start_work", sa.Date(), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("cv", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cccd"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("mst"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employees")
    op.drop_table("tax_policies")
    op.drop_table("positions")
    op.drop_table("insurance_policies")
    op.drop_table("departments")
    op.drop_table("contracttypes")
    op.execute("DROP TYPE taxtype")
    op.execute("DROP TYPE insurancetype")
    op.execute("DROP TYPE gender")
    op.execute("DROP TYPE nationality")

    # ### end Alembic commands ###
