"""delete schedule_details table

Revision ID: 40f2ba24035e
Revises: 82069284b20b
Create Date: 2024-07-25 17:17:00.738035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40f2ba24035e"
down_revision: Union[str, None] = "82069284b20b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_details")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_details",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("schedule_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("shift_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("day", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.Column(
            "created_by", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["schedules.id"], name="schedule_details_schedule_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shifts.id"], name="schedule_details_shift_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "id", "schedule_id", "shift_id", "day", name="schedule_details_pkey"
        ),
    )
    # ### end Alembic commands ###
