"""remove payment method from contract history

Revision ID: 432264609673
Revises: dae710276827
Create Date: 2024-10-04 11:33:21.596802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "432264609673"
down_revision: Union[str, None] = "dae710276827"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contract_histories", "payment_method")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_histories",
        sa.Column(
            "payment_method",
            postgresql.ENUM("CASH", "BANK", name="paymentmethod"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
