"""Add shift_per_day field for schedules table

Revision ID: 4ed5c224a963
Revises: 8b8d6e1ad32e
Create Date: 2024-08-01 09:04:06.518423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ed5c224a963"
down_revision: Union[str, None] = "8b8d6e1ad32e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column("shift_per_day", sa.Integer(), nullable=True, server_default="2"),
    )
    op.alter_column("schedules", "shift_per_day", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "shift_per_day")
    # ### end Alembic commands ###
