"""update model

Revision ID: 696650d1d25a
Revises: 5cd3ab0b4abc
Create Date: 2024-08-10 16:22:28.190488

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "696650d1d25a"
down_revision: Union[str, None] = "5cd3ab0b4abc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
