"""update contract history

Revision ID: 7382c93ddec2
Revises: 432264609673
Create Date: 2024-10-22 09:48:29.860391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7382c93ddec2"
down_revision: Union[str, None] = "432264609673"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_histories", sa.Column("department_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "contract_histories", sa.Column("position_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "contract_histories", sa.Column("schedule_id", sa.Integer(), nullable=True)
    )

    # Update existing rows with values from employees table
    op.execute(
        """
        UPDATE contract_histories ch
        SET department_id = e.department_id,
            position_id = e.position_id,
            schedule_id = e.schedule_id
        FROM employees e
        WHERE ch.employee_id = e.id
    """
    )

    # Now make the columns NOT NULL
    op.alter_column(
        "contract_histories",
        "department_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "contract_histories", "position_id", existing_type=sa.Integer(), nullable=False
    )
    op.alter_column(
        "contract_histories", "schedule_id", existing_type=sa.Integer(), nullable=False
    )
    op.create_foreign_key(
        None, "contract_histories", "departments", ["department_id"], ["id"]
    )
    op.create_foreign_key(
        None, "contract_histories", "positions", ["position_id"], ["id"]
    )
    op.create_foreign_key(
        None, "contract_histories", "schedules", ["schedule_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contract_histories", type_="foreignkey")
    op.drop_constraint(None, "contract_histories", type_="foreignkey")
    op.drop_constraint(None, "contract_histories", type_="foreignkey")
    op.drop_column("contract_histories", "schedule_id")
    op.drop_column("contract_histories", "position_id")
    op.drop_column("contract_histories", "department_id")
    # ### end Alembic commands ###
