"""refactor id field for schedule_details table

Revision ID: 76fe5d185772
Revises: f9d0ff5c02a9
Create Date: 2024-07-27 11:51:39.763245

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "76fe5d185772"
down_revision: Union[str, None] = "f9d0ff5c02a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
