"""delete schedule_details table

Revision ID: 7891d7f7d302
Revises: 87f6d3827059
Create Date: 2024-07-25 17:36:13.627834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7891d7f7d302"
down_revision: Union[str, None] = "87f6d3827059"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_details")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_details",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("schedule_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("shift_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "day",
            postgresql.ENUM(
                "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", name="day"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_by", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["schedules.id"], name="schedule_details_schedule_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shifts.id"], name="schedule_details_shift_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "id", "schedule_id", "shift_id", "day", name="schedule_details_pkey"
        ),
        sa.UniqueConstraint(
            "schedule_id", "shift_id", "day", name="uq_schedule_shift_day"
        ),
    )
    # ### end Alembic commands ###
