"""add companies table

Revision ID: 7a4c0ba90119
Revises: d633ae0519b8
Create Date: 2024-12-28 23:29:38.584829

"""

import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a4c0ba90119"
down_revision: Union[str, None] = "d633ae0519b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.execute(
        """
        INSERT INTO companies (id, code, name, created_by, created_at, updated_at)
        VALUES (0, 'DEFAULT', 'Default Company', 'SYSTEM', :timestamp, :timestamp)
        """,
        {"timestamp": datetime.now()},
    )

    op.add_column(
        "attendances",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "attendances", "companies", ["company_id"], ["id"])
    op.add_column(
        "contract_histories",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(
        None, "contract_histories", "companies", ["company_id"], ["id"]
    )
    op.add_column(
        "departments",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "departments", "companies", ["company_id"], ["id"])
    op.add_column(
        "dependants",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "dependants", "companies", ["company_id"], ["id"])
    op.add_column(
        "employees",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "employees", "companies", ["company_id"], ["id"])
    op.add_column(
        "insurance_policies",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(
        None, "insurance_policies", "companies", ["company_id"], ["id"]
    )
    op.add_column(
        "overtimes",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "overtimes", "companies", ["company_id"], ["id"])
    op.add_column(
        "payroll_managements",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(
        None, "payroll_managements", "companies", ["company_id"], ["id"]
    )
    op.add_column(
        "positions",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "positions", "companies", ["company_id"], ["id"])
    op.add_column(
        "schedule_details",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "schedule_details", "companies", ["company_id"], ["id"])
    op.add_column(
        "schedules",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "schedules", "companies", ["company_id"], ["id"])
    op.add_column(
        "shifts",
        sa.Column("company_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(None, "shifts", "companies", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("companies")
    op.drop_constraint(None, "shifts", type_="foreignkey")
    op.drop_column("shifts", "company_id")
    op.drop_constraint(None, "schedules", type_="foreignkey")
    op.drop_column("schedules", "company_id")
    op.drop_constraint(None, "schedule_details", type_="foreignkey")
    op.drop_column("schedule_details", "company_id")
    op.drop_constraint(None, "positions", type_="foreignkey")
    op.drop_column("positions", "company_id")
    op.drop_constraint(None, "payroll_managements", type_="foreignkey")
    op.drop_column("payroll_managements", "company_id")
    op.drop_constraint(None, "overtimes", type_="foreignkey")
    op.drop_column("overtimes", "company_id")
    op.drop_constraint(None, "insurance_policies", type_="foreignkey")
    op.drop_column("insurance_policies", "company_id")
    op.drop_constraint(None, "employees", type_="foreignkey")
    op.drop_column("employees", "company_id")
    op.drop_constraint(None, "dependants", type_="foreignkey")
    op.drop_column("dependants", "company_id")
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.drop_column("departments", "company_id")
    op.drop_constraint(None, "contract_histories", type_="foreignkey")
    op.drop_column("contract_histories", "company_id")
    op.drop_constraint(None, "attendances", type_="foreignkey")
    op.drop_column("attendances", "company_id")
    # ### end Alembic commands ###
