"""update schedule_id in contract history

Revision ID: 81070c4782db
Revises: 7382c93ddec2
Create Date: 2024-10-22 14:45:53.399428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81070c4782db"
down_revision: Union[str, None] = "7382c93ddec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_histories", "schedule_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_histories", "schedule_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
