"""refactor schedules table

Revision ID: 82069284b20b
Revises: 1874d0773bf8
Create Date: 2024-07-25 16:33:09.350923

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "82069284b20b"
down_revision: Union[str, None] = "1874d0773bf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
