"""add is_holiday for attendance

Revision ID: 8708740d6360
Revises: 076c14c8ef75
Create Date: 2024-11-01 17:44:35.288941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8708740d6360"
down_revision: Union[str, None] = "076c14c8ef75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attendances", sa.Column("is_holiday", sa.Boolean(), nullable=True))
    connection = op.get_bind()

    # Update null cccd_date to current date
    connection.execute(
        sa.text(
            """
        UPDATE attendances
        SET is_holiday = FALSE
        WHERE is_holiday IS NULL
    """
        )
    )

    op.alter_column(
        "attendances", "is_holiday", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attendances", "is_holiday")
    # ### end Alembic commands ###
