"""refactor schedule_details id

Revision ID: 87f6d3827059
Revises: f919c9c1bac6
Create Date: 2024-07-25 17:33:42.850075

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "87f6d3827059"
down_revision: Union[str, None] = "f919c9c1bac6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
