"""refactor schedule_id field for employees table

Revision ID: 8b8d6e1ad32e
Revises: 76fe5d185772
Create Date: 2024-07-27 11:54:24.020513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b8d6e1ad32e"
down_revision: Union[str, None] = "76fe5d185772"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "schedule_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "schedule_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
