"""update PayrollScheduleDetail

Revision ID: bff19914acc0
Revises: f53d8ddbad4c
Create Date: 2024-07-24 20:41:33.777781

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bff19914acc0"
down_revision: Union[str, None] = "f53d8ddbad4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
