"""update insurances table

Revision ID: d633ae0519b8
Revises: 2ecde9567dd3
Create Date: 2024-12-03 04:02:42.844861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d633ae0519b8"
down_revision: Union[str, None] = "2ecde9567dd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("insurance_policies", "is_active")
    op.drop_column("insurance_policies", "based_on")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "insurance_policies",
        sa.Column(
            "based_on",
            postgresql.ENUM(
                "BasicSalary", "TotalSalary", "CustomByEmployee", name="insurancetype"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "insurance_policies",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
