"""update cascade for contract history and dependant

Revision ID: dabc700f103a
Revises: 81070c4782db
Create Date: 2024-10-22 15:57:59.552029

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dabc700f103a"
down_revision: Union[str, None] = "81070c4782db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "contract_histories_employee_id_fkey", "contract_histories", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "contract_histories",
        "employees",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("dependants_employee_id_fkey", "dependants", type_="foreignkey")
    op.create_foreign_key(
        None, "dependants", "employees", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dependants", type_="foreignkey")
    op.create_foreign_key(
        "dependants_employee_id_fkey",
        "dependants",
        "employees",
        ["employee_id"],
        ["id"],
    )
    op.drop_constraint(None, "contract_histories", type_="foreignkey")
    op.create_foreign_key(
        "contract_histories_employee_id_fkey",
        "contract_histories",
        "employees",
        ["employee_id"],
        ["id"],
    )
    # ### end Alembic commands ###
