"""update week_schedule_detail table

Revision ID: f53d8ddbad4c
Revises: 787e8021c5a0
Create Date: 2024-07-24 20:36:07.355480

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f53d8ddbad4c"
down_revision: Union[str, None] = "787e8021c5a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
