"""refactor schedule_details primary_key

Revision ID: f919c9c1bac6
Revises: 9be61f711669
Create Date: 2024-07-25 17:31:53.373542

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f919c9c1bac6"
down_revision: Union[str, None] = "9be61f711669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_schedule_shift_day", "schedule_details", ["schedule_id", "shift_id", "day"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_schedule_shift_day", "schedule_details", type_="unique")
    # ### end Alembic commands ###
