"""refactor schedules table

Revision ID: fe374b53155e
Revises: 1ba67378bf85
Create Date: 2024-07-25 11:28:19.291475

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fe374b53155e"
down_revision: Union[str, None] = "1ba67378bf85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
