"""update payroll management table

Revision ID: ffc8327da2d3
Revises: 79e9538b3349
Create Date: 2024-09-27 12:33:31.877356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffc8327da2d3"
down_revision: Union[str, None] = "79e9538b3349"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dependants",
        "relationship",
        existing_type=postgresql.ENUM(
            "CHILD", "PARENT", "COUPLE", "OTHER", name="dependantrelationship"
        ),
        nullable=False,
    )
    op.add_column(
        "payroll_managements",
        sa.Column("work_days_standard", sa.Float(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payroll_managements", "work_days_standard")
    op.alter_column(
        "dependants",
        "relationship",
        existing_type=postgresql.ENUM(
            "CHILD", "PARENT", "COUPLE", "OTHER", name="dependantrelationship"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
